// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmNQFOWIHLu8UVt4KWzK1o6JLmUO9CBE',
    appId: '1:918244282384:web:765276ab983643c478ba95',
    messagingSenderId: '918244282384',
    projectId: 'demoproject-8d727',
    authDomain: 'demoproject-8d727.firebaseapp.com',
    storageBucket: 'demoproject-8d727.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIeYeiCalwHbaS-t0tRWe3iemWC6sNmk',
    appId: '1:918244282384:android:5cd1c1fc937cbb3378ba95',
    messagingSenderId: '918244282384',
    projectId: 'demoproject-8d727',
    storageBucket: 'demoproject-8d727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQNAEK101Y7GcC-SAP_Ouc0eXlaQdlbWk',
    appId: '1:918244282384:ios:2fa695cb89de5a7278ba95',
    messagingSenderId: '918244282384',
    projectId: 'demoproject-8d727',
    storageBucket: 'demoproject-8d727.appspot.com',
    iosBundleId: 'com.example.fbsetting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQNAEK101Y7GcC-SAP_Ouc0eXlaQdlbWk',
    appId: '1:918244282384:ios:d003a9b2a9fa626178ba95',
    messagingSenderId: '918244282384',
    projectId: 'demoproject-8d727',
    storageBucket: 'demoproject-8d727.appspot.com',
    iosBundleId: 'com.example.fbsetting.RunnerTests',
  );
}
